"""empty message

Revision ID: 6477628a6e3f
Revises: 
Create Date: 2022-10-03 12:53:14.434721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6477628a6e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_catalogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stac_version', sa.Text(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('stac_ingestion_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_finished', sa.DateTime(), nullable=True),
    sa.Column('source_stac_api_url', sa.Text(), nullable=True),
    sa.Column('target_stac_api_url', sa.Text(), nullable=True),
    sa.Column('update', sa.Boolean(), nullable=True),
    sa.Column('newly_stored_collections_count', sa.Integer(), nullable=True),
    sa.Column('newly_stored_collections', sa.Text(), nullable=True),
    sa.Column('updated_collections_count', sa.Integer(), nullable=True),
    sa.Column('updated_collections', sa.Text(), nullable=True),
    sa.Column('newly_stored_items_count', sa.Integer(), nullable=True),
    sa.Column('updated_items_count', sa.Integer(), nullable=True),
    sa.Column('already_stored_items_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_stac_api_url'], ['public_catalogs.url'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stac_ingestion_status_source_stac_api_url'), 'stac_ingestion_status', ['source_stac_api_url'], unique=False)
    op.create_table('stored_search_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bbox', sa.Text(), nullable=True),
    sa.Column('datetime', sa.Text(), nullable=True),
    sa.Column('collection', sa.Text(), nullable=True),
    sa.Column('used_search_parameters', sa.Text(), nullable=False),
    sa.Column('associated_catalog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['associated_catalog_id'], ['public_catalogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('used_search_parameters')
    )
    op.create_index(op.f('ix_stored_search_parameters_associated_catalog_id'), 'stored_search_parameters', ['associated_catalog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_search_parameters_associated_catalog_id'), table_name='stored_search_parameters')
    op.drop_table('stored_search_parameters')
    op.drop_index(op.f('ix_stac_ingestion_status_source_stac_api_url'), table_name='stac_ingestion_status')
    op.drop_table('stac_ingestion_status')
    op.drop_table('public_catalogs')
    # ### end Alembic commands ###
