"""empty message

Revision ID: 2f6e84ca5510
Revises: 6e50948c5e42
Create Date: 2022-10-04 12:14:02.158612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6e84ca5510'
down_revision = '6e50948c5e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_catalogs', 'stac_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_catalogs', sa.Column('stac_version', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
