"""empty message

Revision ID: 9d9319268fa5
Revises: ff967b1d8dab
Create Date: 2022-10-11 12:11:26.276691

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9d9319268fa5'
down_revision = 'ff967b1d8dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_collections',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('temporal_extent_start', sa.DateTime(), nullable=True),
    sa.Column('temporal_extent_end', sa.DateTime(), nullable=True),
    sa.Column('spatial_extent', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # op.create_index('idx_private_collections_spatial_extent', 'private_collections', ['spatial_extent'], unique=False, postgresql_using='gist')
   #  op.drop_table('spatial_ref_sys')
    op.alter_column('public_collections', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('public_collections', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('_id_parent_catalog_uc', 'public_collections', ['id', 'parent_catalog'])
    op.drop_constraint('public_collections_parent_catalog_fkey', 'public_collections', type_='foreignkey')
    op.create_foreign_key(None, 'public_collections', 'public_catalogs', ['parent_catalog'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_collections', type_='foreignkey')
    op.create_foreign_key('public_collections_parent_catalog_fkey', 'public_collections', 'public_catalogs', ['parent_catalog'], ['id'])
    op.drop_constraint('_id_parent_catalog_uc', 'public_collections', type_='unique')
    op.alter_column('public_collections', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('public_collections', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # op.drop_index('idx_private_collections_spatial_extent', table_name='private_collections', postgresql_using='gist')
    op.drop_table('private_collections')
    # ### end Alembic commands ###
